In [6]:
from torch.utils.data import DataLoader
from data import LRHR_Dataset
from utils import show_img


dataset = LRHR_Dataset(r'C:\Users\kingi\Desktop\result', r'C:\Users\kingi\Desktop\result2')
# dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

for filename, img_HR, img_LR in dataset:
    print(filename)
    print(img_HR.shape)
    print(img_HR[0][:1][:1])
    print(img_LR[0][:1][:1])

000012_400_5000
torch.Size([3, 112, 96])
tensor([[0.2000, 0.1686, 0.1686, 0.1608, 0.1725, 0.1608, 0.1608, 0.1686, 0.1725,
         0.1725, 0.1725, 0.1843, 0.1882, 0.1725, 0.1725, 0.1647, 0.1490, 0.1216,
         0.1216, 0.1098, 0.0941, 0.0863, 0.0863, 0.0745, 0.0667, 0.0627, 0.0627,
         0.0627, 0.0667, 0.0706, 0.0706, 0.0667, 0.0667, 0.0706, 0.0706, 0.0745,
         0.0745, 0.0863, 0.0863, 0.0941, 0.0980, 0.1020, 0.1020, 0.1059, 0.1098,
         0.1098, 0.1098, 0.1098, 0.1137, 0.1176, 0.1176, 0.1176, 0.1176, 0.1216,
         0.1216, 0.1255, 0.1333, 0.1255, 0.1255, 0.1294, 0.1294, 0.1294, 0.1294,
         0.1098, 0.1020, 0.0980, 0.0980, 0.0980, 0.0980, 0.0980, 0.0980, 0.1020,
         0.1020, 0.1020, 0.1020, 0.1176, 0.1216, 0.1333, 0.1333, 0.1647, 0.1961,
         0.2157, 0.2157, 0.2314, 0.2392, 0.2275, 0.2275, 0.2196, 0.2157, 0.2000,
         0.2000, 0.2039, 0.1961, 0.2196, 0.2196, 0.2902]])
tensor([[0.2000, 0.1686, 0.1686, 0.1608, 0.1725, 0.1608, 0.1608, 0.1686, 0.1725,
         

         0.6784, 0.6549, 0.6667, 0.6471, 0.6471, 0.6000]])


In [ ]:
dataset = Dataset(r"C:\Users\kingi\Desktop\result")
for img_name, img in dataset:
    print(img.shape)
    show_img(img)
    break

In [9]:
if 1:
    import numpy as np
np.ndarray([1,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
class A:
    a = 0
    def __init__(self):
        self.b = 1
        A.a += 1
    def f(self):
        print(self.a)
        print(self.b)
a = A()
b = A()
a.f()
b.f()

2
1
2
1
